# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    task_worker:
        class: AppBundle\Task\TaskWorker
        arguments:
            - "@logger"
            - "@doctrine"

    create_tasks.command:
        class: AppBundle\Command\CreateTasksCommand
        arguments:
            - "@mcfedr_queue_manager.registry"
            - "@logger"
        tags:
            - { name: console.command }
